import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "@/components/ui/table";

function DCByLevelsTable() {
    return ( 
        <>
        <Table>
        <TableHeader >
            <TableRow>
                <TableHead className="font-bold">Level</TableHead>
                <TableHead className="font-bold">DC</TableHead>
            </TableRow>
        </TableHeader>
        <TableBody>
            <TableRow>
                <TableCell>0</TableCell>
                <TableCell>14</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>1</TableCell>
                <TableCell>15</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>2</TableCell>
                <TableCell>16</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>3</TableCell>
                <TableCell>18</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>4</TableCell>
                <TableCell>19</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>5</TableCell>
                <TableCell>20</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>6</TableCell>
                <TableCell>22</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>7</TableCell>
                <TableCell>23</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>8</TableCell>
                <TableCell>24</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>9</TableCell>
                <TableCell>26</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>10</TableCell>
                <TableCell>27</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>11</TableCell>
                <TableCell>28</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>12</TableCell>
                <TableCell>30</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>13</TableCell>
                <TableCell>31</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>14</TableCell>
                <TableCell>32</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>15</TableCell>
                <TableCell>34</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>16</TableCell>
                <TableCell>35</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>17</TableCell>
                <TableCell>36</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>18</TableCell>
                <TableCell>38</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>19</TableCell>
                <TableCell>39</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>20</TableCell>
                <TableCell>40</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>21</TableCell>
                <TableCell>42</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>22</TableCell>
                <TableCell>44</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>23</TableCell>
                <TableCell>46</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>24</TableCell>
                <TableCell>48</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>25</TableCell>
                <TableCell>50</TableCell>
            </TableRow>
        </TableBody>
    </Table>
    </>
    )
}

export default DCByLevelsTable;