import {useState} from 'react';

function TavernNames() {

    const [tavernName, setTavernName] = useState("...");

    const materials = [
        "Iron",
        "Aluminium",
        "Copper",
        "Gold",
        "Silver",
        "Lead",
        "Zinc",
        "Nickel",
        "Tin",
        "Titanium",
        "Magnesium",
        "Platinum",
        "Cobalt",
        "Chrome",
        "Mercury",
        "Tungsten",
        "Uranium",
        "Palladium",
        "Cadmium",
        "Vanadium",
        "Manganese",
        "Oak",
        "Maple",
        "Pine",
        "Cedar",
        "Walnut",
        "Cherry",
        "Mahogany",
        "Teak",
        "Birch",
        "Ash",
        "Granite",
        "Marble",
        "Limestone",
        "Sandstone",
        "Slate",
        "Basalt",
        "Quartz",
        "Obsidian",
        "Jade",
        "Onyx",
        "Rusty",
        "Dirty",
        "Salty",
        "Red",
        "Orange",
        "Yellow",
        "Green",
        "Blue",
        "Indigo",
        "Purple",
        "Black",
        "White",
        "Grey",
        "Smiling",
        "Laughing",
        "Crying",
        "Snarling",
        "Roaring",
        "Grinning",
        "Frowning",
        "Smirking",
        "Howling",
        "Growling",
        "Scowling",
        "Pouting",
        "Yawning",
        "Screaming",
        "Shouting",
        "Whispering",
        "Winking",
        "Blinking",
        "Staring",
        "Glaring",
        "Leering",
        "Sneering",
        "Grimacing",
        "Gasping",
        "Chuckling",
        "Giggling",
        "Snickering",
        "Guffawing",
        "Bellowing",
        "Hissing",
        "Raging",
        "Pondering",
        "Meditating",
        "Dreaming",
        "Scheming",
        "Prancing",
        "Dancing",
        "Frolicking",
        "Lurking",
        "Stalking",
        "Pouncing",
        "Flying",
        "Crawling",
        "Galloping",
        "Charging",
    ];

    const nouns = [
        "Dragon",
        "Wyvern",
        "Velociraptor",
        "Phoenix",
        "Griffin",
        "Unicorn",
        "Kraken",
        "Mermaid",
        "Centaur",
        "Werewolf",
        "Basilisk",
        "Chimera",
        "Pegasus",
        "Minotaur",
        "Yeti",
        "Elf",
        "Dwarf",
        "Orc",
        "Goblin",
        "Troll",
        "Fairy",
        "Vampire",
        "Leviathan",
        "Kitsune",
        "Banshee",
        "Cerberus",
        "Harpy",
        "Sphinx",
        "Gorgon",
        "Cyclops",
        "Kappa",
        "Selkie",
        "Roc",
        "Kelpie",
        "Wendigo",
        "Thunderbird",
        "Nymph",
        "Satyr",
        "Faun",
        "Gargoyle",
        "Zombie",
        "Ghoul",
        "Revenant",
        "Lich",
        "Shapeshifter",
        "Ent",
        "Dryad",
        "Treant",
        "Krakenling",
        "Peryton",
        "Jackalope",
        "Chupacabra",
        "Bunyip",
        "Quetzalcoatl",
        "Jörmungandr",
        "Fenrir",
        "Garuda",
        "Naga",
        "Oni",
        "Tengu",
        "Yokai",
        "Skinwalker",
        "Wraith",
        "Barghest",
        "Cockatrice",
        "Hippogriff",
        "Simurgh",
        "Ammit",
        "Anubis",
        "Charybdis",
        "Scylla",
        "Tiamat",
        "Bahamut",
        "Human",
        "Leshy",
        "Strix",
        "Grippli",
        "Rakshasa",
        "Boggard",
        "Kobold",
        "Troglodyte",
        "Thriae",
    ];

    const roll = (max, min = 0) => {
        return ( Math.floor(Math.random() * (max - min) + min) )
    }

    const generateTavernName = () => {
        let materialRoll = roll(materials.length - 1);
        let nounRoll = roll(nouns.length - 1);
        let material = materials[materialRoll];
        let noun = nouns[nounRoll];

        setTavernName(`The ${material} ${noun}`);
    }

    return(
        <>
        <div className="flex flex-col justify-center">
            <h3 className="text-2xl text-center mb-[2em] mt-[1em]">{tavernName}</h3>
            <button
            className="text-white font-bold py-2 px-4 rounded-full bg-transparent border hover:border-transparent hover:bg-[--clr-surface-tonal-a30] text-center"
            onClick={generateTavernName}
            >
                New Tavern
            </button>
        </div>
        </>
    )
}

export default TavernNames;